/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_activitylifecycle_TestJNI */

#ifndef _Included_com_example_activitylifecycle_TestJNI
#define _Included_com_example_activitylifecycle_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_activitylifecycle_TestJNI
 * Method:    Init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_activitylifecycle_TestJNI_Init
  (JNIEnv *, jobject);

/*
 * Class:     com_example_activitylifecycle_TestJNI
 * Method:    Add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_activitylifecycle_TestJNI_Add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_activitylifecycle_TestJNI
 * Method:    Destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_activitylifecycle_TestJNI_Destory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
